In [11]:
import pandas as pd
import numpy as np
from datetime import datetime
import matplotlib.pyplot as plt
from functools import reduce

In [13]:
df = pd.read_excel("C:/Users/adria/OneDrive/Escritorio/Repaso Python Anlisis de datos/Tarjeta_Credito.xlsx")
df

,Id_Transaccion,Cliente,Fecha_Compra,Monto_Pesos,Cuotas,Categoria,Producto,Canal_Pago,Satisfaccion_Cliente,Fecha_Cierre_Ciclo
0,TX1001,Diego Rodriguez,2026-04-18,7185.00,1,Gastronomía,Delivery Fin de Semana,Online (E-Commerce),4,2026-05-10
1,TX1002,Carlos Mendoza,2026-04-25,22668.62,1,Combustible / \nTransporte,Carga Nafta Premium,Presencial (Posnet),5,2026-05-10
2,TX1003,Carlos Mendoza,2026-05-01,35123.63,1,Supermercado,Alimentos y Bebidas,Online (E-Commerce),4,2026-05-10
3,TX1004,Javier Maidana,2026-05-02,47466.72,1,Supermercado,Compra Mensual Mayorista,Online (E-Commerce),4,2026-05-10
4,TX1005,Ana Maria Silva,2026-04-12,27627.56,1,Indumentaria,Zapatillas Deportivas,Presencial (Posnet),4,2026-05-10
...,...,...,...,...,...,...,...,...,...,...
144,TX1145,Diego Rodriguez,2026-05-01,14036.03,1,Combustible / Transporte,Carga Nafta Premium,Presencial (Posnet),5,2026-05-10
145,TX1146,Gustavo Peralta,2026-05-05,13010.51,1,Gastronomía,Cena Restaurante,Online (E-Commerce),4,2026-05-10
146,TX1147,Gustavo Peralta,2026-04-11,5771.62,1,Gastronomía,Cafetería,Online (E-Commerce),4,2026-05-10
147,TX1148,Florencia Benitez,2026-05-02,15309.83,1,Combustible / Transporte,Carga Nafta Premium,Presencial (Posnet),5,2026-05-10
148,TX1149,Diego Rodriguez,2026-04-14,4863.02,1,Gastronomía,Cafetería,Online (E-Commerce),5,2026-05-10

In [ ]:
# Nuevas COLUMNAS creadas

In [15]:
df["Dia_Fecha"] = df["Fecha_Compra"].dt.day # Obtener dias de la fecha

#Columna Periodo_Compra
condition = [
    df["Dia_Fecha"] >= 21,
    df["Dia_Fecha"] >=11
]
choice = ("Despues del dia 21","Entre el dia 11 y 20")
df["Periodo_Compra"] = np.select(condition, choice,default="Entre el dia 1 y 10")

#Columna Clasificacion_Satisfaccion_Cliente
condition = [
    df["Satisfaccion_Cliente"] >= 4,
    df["Satisfaccion_Cliente"] == 3
] 
choice = ("Alta","Media")
df["Clasificacion_Satisfaccion_Cliente"] = np.select(condition,choice,default="Baja")

#Clasificacion_Tipo_Compra
condition = [
    df["Monto_Pesos"] >= 150000,
    df["Monto_Pesos"] >= 80000,
    df["Monto_Pesos"] >= 35000
] 
choice = ("Premiun","Alto", "Estandard")
df["Clasificacion_Tipo_Compra"] = np.select(condition,choice,default="Bajo")
df

# Plan_Cuotas
condition = [
    df["Cuotas"] == 1,
    df["Cuotas"] == 3,
    df["Cuotas"] == 6,
]
choice = ("Plan 1 cuota","Plan 3 cuotas","Plan 6 cuotas")
df["Plan_Cuotas"] = np.select(condition,choice,default="Plan 12 coutas")
df

,Id_Transaccion,Cliente,Fecha_Compra,Monto_Pesos,Cuotas,Categoria,Producto,Canal_Pago,Satisfaccion_Cliente,Fecha_Cierre_Ciclo,Dia_Fecha,Periodo_Compra,Clasificacion_Satisfaccion_Cliente,Clasificacion_Tipo_Compra,Plan_Cuotas
0,TX1001,Diego Rodriguez,2026-04-18,7185.00,1,Gastronomía,Delivery Fin de Semana,Online (E-Commerce),4,2026-05-10,18,Entre el dia 11 y 20,Alta,Bajo,Plan 1 cuota
1,TX1002,Carlos Mendoza,2026-04-25,22668.62,1,Combustible / \nTransporte,Carga Nafta Premium,Presencial (Posnet),5,2026-05-10,25,Despues del dia 21,Alta,Bajo,Plan 1 cuota
2,TX1003,Carlos Mendoza,2026-05-01,35123.63,1,Supermercado,Alimentos y Bebidas,Online (E-Commerce),4,2026-05-10,1,Entre el dia 1 y 10,Alta,Estandard,Plan 1 cuota
3,TX1004,Javier Maidana,2026-05-02,47466.72,1,Supermercado,Compra Mensual Mayorista,Online (E-Commerce),4,2026-05-10,2,Entre el dia 1 y 10,Alta,Estandard,Plan 1 cuota
4,TX1005,Ana Maria Silva,2026-04-12,27627.56,1,Indumentaria,Zapatillas Deportivas,Presencial (Posnet),4,2026-05-10,12,Entre el dia 11 y 20,Alta,Bajo,Plan 1 cuota
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
144,TX1145,Diego Rodriguez,2026-05-01,14036.03,1,Combustible / Transporte,Carga Nafta Premium,Presencial (Posnet),5,2026-05-10,1,Entre el dia 1 y 10,Alta,Bajo,Plan 1 cuota
145,TX1146,Gustavo Peralta,2026-05-05,13010.51,1,Gastronomía,Cena Restaurante,Online (E-Commerce),4,2026-05-10,5,Entre el dia 1 y 10,Alta,Bajo,Plan 1 cuota
146,TX1147,Gustavo Peralta,2026-04-11,5771.62,1,Gastronomía,Cafetería,Online (E-Commerce),4,2026-05-10,11,Entre el dia 11 y 20,Alta,Bajo,Plan 1 cuota
147,TX1148,Florencia Benitez,2026-05-02,15309.83,1,Combustible / Transporte,Carga Nafta Premium,Presencial (Posnet),5,2026-05-10,2,Entre el dia 1 y 10,Alta,Bajo,Plan 1 cuota
148,TX1149,Diego Rodriguez,2026-04-14,4863.02,1,Gastronomía,Cafetería,Online (E-Commerce),5,2026-05-10,14,Entre el dia 11 y 20,Alta,Bajo,Plan 1 cuota

In [ ]:
## - Analisis de CLIENTES - Se dividio el analisis en tres partes (intensidad, frecuencia, montos)

In [ ]:
## 1- INTENSIDAD DE COMPRA

In [17]:
#Agrupar por cliente y fecha y devolver el tamaño de esa combinacion, por ejemplo 1, 2 , 3 compras por dia y cliente
intensidad = df.groupby(['Cliente','Fecha_Compra']).size().reset_index(name='Compras_por_dia')
analisis_compras = intensidad.groupby("Cliente").agg(
    compras_Xdia_promedio = ("Compras_por_dia","mean"),
    Cantidad_Compras = ("Compras_por_dia","sum")
).round(2).sort_values(by="Cantidad_Compras",ascending=False)
analisis_compras["%Compras"] = ((analisis_compras["Cantidad_Compras"] / analisis_compras["Cantidad_Compras"].sum())*100).round(2).astype(str) + "%"
analisis_compras

                   compras_Xdia_promedio  Cantidad_Compras %Compras
Cliente
Florencia Benitez                   1.64                23   15.44%
Gustavo Peralta                     1.92                23   15.44%
Javier Maidana                      1.67                20   13.42%
Diego Rodriguez                     1.90                19   12.75%
Ana Maria Silva                     1.31                17   11.41%
Carlos Mendoza                      1.33                16   10.74%
Lucia Fernandez                     1.50                 9    6.04%
Camila Gomez                        1.14                 8    5.37%
Mariano Rossi                       1.14                 8    5.37%
Sofia Martinez                      1.00                 6    4.03%

In [ ]:
## 2 - FRECUENCIA DE COMPRA

In [19]:
df_unico = df.drop_duplicates(subset=['Cliente','Fecha_Compra']).sort_values(['Cliente','Fecha_Compra'])
df_unico["Fecha_Compra_Anterior"] = df_unico.groupby("Cliente")["Fecha_Compra"].shift(1)
df_unico["Dias_Entre_Compras"] = (df_unico["Fecha_Compra"] - df_unico["Fecha_Compra_Anterior"]).dt.days
analisis_dias = df_unico.groupby("Cliente").agg(
    Frecuencia_Compra_Dias = ("Dias_Entre_Compras","mean"),
    Fecha_Ultima_Compra = ("Fecha_Compra","max")
).round(2).sort_values(by="Frecuencia_Compra_Dias")
analisis_dias["Fecha_de_Cierre"] = df_unico["Fecha_Cierre_Ciclo"].iloc[0]
analisis_dias["Dias_Desde_Ultimo_Consumo"] = (analisis_dias["Fecha_de_Cierre"] - analisis_dias["Fecha_Ultima_Compra"]).dt.days
analisis_dias["Desvio_del_Promedio"] = analisis_dias["Dias_Desde_Ultimo_Consumo"] - analisis_dias["Frecuencia_Compra_Dias"]
condition = [
    analisis_dias["Desvio_del_Promedio"] > 0,
     analisis_dias["Desvio_del_Promedio"] <=  0
]
choice = ("dias por encima del promedio","dias por debajo del promedio")
analisis_dias["Detalle_Desvio"] = np.select(condition, choice,default="otro")
analisis_dias

,Frecuencia_Compra_Dias,Fecha_Ultima_Compra,Fecha_de_Cierre,Dias_Desde_Ultimo_Consumo,Desvio_del_Promedio,Detalle_Desvio
Cliente,,,,,,
Florencia Benitez,1.62,2026-05-02,2026-05-10,8,6.38,dias por encima del promedio
Javier Maidana,2.00,2026-05-05,2026-05-10,5,3.00,dias por encima del promedio
Gustavo Peralta,2.27,2026-05-06,2026-05-10,4,1.73,dias por encima del promedio
Ana Maria Silva,2.33,2026-05-09,2026-05-10,1,-1.33,dias por debajo del promedio
Carlos Mendoza,2.55,2026-05-09,2026-05-10,1,-1.55,dias por debajo del promedio
Camila Gomez,2.67,2026-04-28,2026-05-10,12,9.33,dias por encima del promedio
Diego Rodriguez,2.67,2026-05-07,2026-05-10,3,0.33,dias por encima del promedio
Mariano Rossi,4.00,2026-05-05,2026-05-10,5,1.00,dias por encima del promedio
Sofia Martinez,5.00,2026-05-06,2026-05-10,4,-1.00,dias por debajo del promedio
Lucia Fernandez,5.60,2026-05-09,2026-05-10,1,-4.60,dias por debajo del promedio

In [ ]:
## 3 - ANALISIS FINANCIERO

In [21]:
analisis_financiero = df.groupby("Cliente").agg(
    Ticket_Promedio = ("Monto_Pesos","mean"),
    Monto = ("Monto_Pesos","sum"),
    Satisfaccion_Cliente = ("Satisfaccion_Cliente","mean")
).round(2).sort_values(by="Monto", ascending= False)

analisis_financiero["%Monto"] = ((analisis_financiero["Monto"] / analisis_financiero["Monto"].sum())*100).round(2)
analisis_financiero["%Acumulado_Monto"] = (analisis_financiero["%Monto"]).cumsum().round(2)

analisis_financiero["%Monto"] = analisis_financiero["%Monto"].astype(str) + "%"
analisis_financiero["Ticket_Promedio"] = analisis_financiero["Ticket_Promedio"].apply(lambda x: f"${x:,.2f}".replace(",","X").replace(".",",").replace("X","."))
analisis_financiero["Monto"] = analisis_financiero["Monto"].apply(lambda x: f"${x:,.2f}".replace(",","X").replace(".",",").replace("X","."))

condition = [
    analisis_financiero["%Acumulado_Monto"] <= 85,
    analisis_financiero["%Acumulado_Monto"] <=95 
]
choice = ("A","B")
analisis_financiero["Pareto_ClienteABC"] = np.select(condition,choice,default="C")

analisis_financiero["%Acumulado_Monto"] = analisis_financiero["%Acumulado_Monto"].astype(str) + "%"

analisis_financiero

,Ticket_Promedio,Monto,Satisfaccion_Cliente,%Monto,%Acumulado_Monto,Pareto_ClienteABC
Cliente,,,,,,
Florencia Benitez,"$29.632,75","$681.553,25",4.26,19.86%,19.86%,A
Gustavo Peralta,"$25.455,21","$585.469,92",4.26,17.06%,36.92%,A
Ana Maria Silva,"$23.678,76","$402.538,88",4.18,11.73%,48.65%,A
Carlos Mendoza,"$21.389,83","$342.237,34",4.31,9.97%,58.62%,A
Javier Maidana,"$16.883,82","$337.676,44",4.25,9.84%,68.46%,A
Diego Rodriguez,"$13.671,37","$259.756,10",4.32,7.57%,76.03%,A
Sofia Martinez,"$39.020,70","$234.124,22",4.67,6.82%,82.85%,A
Camila Gomez,"$29.261,10","$234.088,84",4.00,6.82%,89.67%,B
Lucia Fernandez,"$22.971,06","$206.739,56",4.44,6.02%,95.69%,C
Mariano Rossi,"$18.405,26","$147.242,11",4.25,4.29%,99.98%,C

In [ ]:
## 4- UNION DE LOS 3 HALLAZGOS

In [23]:
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 1000)
dfs_analisis_clientes = [analisis_compras,analisis_dias,analisis_financiero]
df_consolidado_analisis_clientes = reduce(
    lambda left, right: pd.merge(left, right, on="Cliente", how="left"), 
    dfs_analisis_clientes)
df_consolidado_analisis_clientes = df_consolidado_analisis_clientes.sort_values(by="Monto", ascending = False)
df_consolidado_analisis_clientes

                   compras_Xdia_promedio  Cantidad_Compras %Compras  Frecuencia_Compra_Dias Fecha_Ultima_Compra Fecha_de_Cierre  Dias_Desde_Ultimo_Consumo  Desvio_del_Promedio                Detalle_Desvio Ticket_Promedio        Monto  Satisfaccion_Cliente  %Monto %Acumulado_Monto Pareto_ClienteABC
Cliente
Florencia Benitez                   1.64                23   15.44%                    1.62          2026-05-02      2026-05-10                          8                 6.38  dias por encima del promedio      $29.632,75  $681.553,25                  4.26  19.86%           19.86%                 A
Gustavo Peralta                     1.92                23   15.44%                    2.27          2026-05-06      2026-05-10                          4                 1.73  dias por encima del promedio      $25.455,21  $585.469,92                  4.26  17.06%           36.92%                 A
Ana Maria Silva                     1.31                17   11.41%                    2.33          2026-05-09      2026-05-10                          1                -1.33  dias por debajo del promedio      $23.678,76  $402.538,88                  4.18  11.73%           48.65%                 A
Carlos Mendoza                      1.33                16   10.74%                    2.55          2026-05-09      2026-05-10                          1                -1.55  dias por debajo del promedio      $21.389,83  $342.237,34                  4.31   9.97%           58.62%                 A
Javier Maidana                      1.67                20   13.42%                    2.00          2026-05-05      2026-05-10                          5                 3.00  dias por encima del promedio      $16.883,82  $337.676,44                  4.25   9.84%           68.46%                 A
Diego Rodriguez                     1.90                19   12.75%                    2.67          2026-05-07      2026-05-10                          3                 0.33  dias por encima del promedio      $13.671,37  $259.756,10                  4.32   7.57%           76.03%                 A
Sofia Martinez                      1.00                 6    4.03%                    5.00          2026-05-06      2026-05-10                          4                -1.00  dias por debajo del promedio      $39.020,70  $234.124,22                  4.67   6.82%           82.85%                 A
Camila Gomez                        1.14                 8    5.37%                    2.67          2026-04-28      2026-05-10                         12                 9.33  dias por encima del promedio      $29.261,10  $234.088,84                  4.00   6.82%           89.67%                 B
Lucia Fernandez                     1.50                 9    6.04%                    5.60          2026-05-09      2026-05-10                          1                -4.60  dias por debajo del promedio      $22.971,06  $206.739,56                  4.44   6.02%           95.69%                 C
Mariano Rossi                       1.14                 8    5.37%                    4.00          2026-05-05      2026-05-10                          5                 1.00  dias por encima del promedio      $18.405,26  $147.242,11                  4.25   4.29%           99.98%                 C

In [ ]:
## ANALISIS POR PERIODO DE COMPRA

In [25]:
analisis_periodo_compras = df.groupby("Periodo_Compra").agg(
    Cantidad_Compras = ("Id_Transaccion","count"),
    Ticket_Promedio = ("Monto_Pesos","mean"),
    Recaudacion = ("Monto_Pesos","sum"),
    Medio_Pago_Mas_Utilizado = ("Canal_Pago",lambda x: x.mode()),
    Tipo_Gasto_Frecuente = ("Clasificacion_Tipo_Compra",lambda x: x.mode()),
    Plan_Cuota_Mas_Usado = ("Plan_Cuotas", lambda x: x.mode())
).round(2).sort_index().sort_values(by="Cantidad_Compras", ascending = False )

analisis_periodo_compras["%Recaudacion"] = ((analisis_periodo_compras["Recaudacion"] / analisis_periodo_compras["Recaudacion"].sum()) 
                                           * 100).round(2).astype(str) + "%"
analisis_periodo_compras["%Compras"] = ((analisis_periodo_compras["Cantidad_Compras"] / analisis_periodo_compras["Cantidad_Compras"].sum()) 
                                        *100).round(2).astype(str) + "%"

analisis_periodo_compras["Ticket_Promedio"] = analisis_periodo_compras["Ticket_Promedio"].apply(lambda x: f"${x:,.2f}".replace(",", "X").replace(".", ",").replace("X", "."))
analisis_periodo_compras["Recaudacion"] = analisis_periodo_compras["Recaudacion"].apply(lambda x: f"${x:,.2f}".replace(",", "X").replace(".", ",").replace("X", "."))

Orden = [
"Cantidad_Compras",
"%Compras",
"Tipo_Gasto_Frecuente",
"Ticket_Promedio",
"Recaudacion",
"%Recaudacion",
"Medio_Pago_Mas_Utilizado",
"Plan_Cuota_Mas_Usado"
]

analisis_periodo_compras = analisis_periodo_compras [Orden]
analisis_periodo_compras

                      Cantidad_Compras %Compras Tipo_Gasto_Frecuente Ticket_Promedio    Recaudacion %Recaudacion Medio_Pago_Mas_Utilizado Plan_Cuota_Mas_Usado
Periodo_Compra
Entre el dia 11 y 20                56   37.58%                 Bajo      $20.275,76  $1.135.442,41       33.09%      Online (E-Commerce)         Plan 1 cuota
Despues del dia 21                  49   32.89%                 Bajo      $26.683,93  $1.307.512,58        38.1%      Online (E-Commerce)         Plan 1 cuota
Entre el dia 1 y 10                 44   29.53%                 Bajo      $22.465,27    $988.471,67       28.81%      Online (E-Commerce)         Plan 1 cuota

In [ ]:
## ANALISIS POR PRODUCTO

In [27]:
analisis_producto = df.groupby("Producto").agg(
    Ventas = ("Id_Transaccion","count"),
    Ticket_Promedio = ("Monto_Pesos","mean"),
    Recaudacion = ("Monto_Pesos","sum"),
    Medio_Pago_Mas_Usado = ("Canal_Pago",lambda x: x.mode()),
    Tipo_Gasto_Frecuente = ("Clasificacion_Tipo_Compra",lambda x: x.mode()),
    Periodo_Con_Mas_Compras = ("Periodo_Compra",lambda x: x.mode()),
    Plan_Cuota_Mas_Usado = ("Plan_Cuotas", lambda x: x.mode())
    
).round(2).sort_values(by = "Recaudacion", ascending = False )

analisis_producto["%Recaudacion"] = ((analisis_producto["Recaudacion"] / analisis_producto["Recaudacion"].sum()) * 100).round(2).astype(str) + "%"
analisis_producto["%Ventas"] = ((analisis_producto["Ventas"] / analisis_producto["Ventas"].sum()) * 100).round(2).astype(str) + "%"
analisis_producto["Ticket_Promedio"] = analisis_producto["Ticket_Promedio"].apply(lambda x: f"${x:,.2f}".replace(",","X").replace(".",",").replace("X","."))
analisis_producto["Recaudacion"] = analisis_producto["Recaudacion"].apply(lambda x: f"${x:,.2f}".replace(",","X").replace(".",",").replace("X","."))

Orden = [
"Ventas",
"%Ventas",
"Ticket_Promedio",
"Recaudacion",
"%Recaudacion",
"Periodo_Con_Mas_Compras",
"Medio_Pago_Mas_Usado",
"Plan_Cuota_Mas_Usado",
"Tipo_Gasto_Frecuente"
]
analisis_producto = analisis_producto[Orden]
analisis_producto

                          Ventas %Ventas Ticket_Promedio  Recaudacion %Recaudacion                     Periodo_Con_Mas_Compras                        Medio_Pago_Mas_Usado Plan_Cuota_Mas_Usado Tipo_Gasto_Frecuente
Producto
Alimentos y Bebidas           14    9.4%      $41.731,32  $584.238,42       17.03%                         Entre el dia 1 y 10                         Online (E-Commerce)         Plan 1 cuota            Estandard
Smartphone Cuotas              4   2.68%     $137.040,50  $548.162,01       15.97%  [Despues del dia 21, Entre el dia 11 y 20]                         Online (E-Commerce)        Plan 3 cuotas      [Alto, Premiun]
Compra Mensual Mayorista       9   6.04%      $60.341,22  $543.070,97       15.83%                        Entre el dia 11 y 20                         Online (E-Commerce)         Plan 1 cuota            Estandard
Carga Nafta Premium           19  12.75%      $15.669,34  $297.717,46        8.68%                         Entre el dia 1 y 10                         Presencial (Posnet)         Plan 1 cuota                 Bajo
Artículos de Limpieza          7    4.7%      $36.628,78  $256.401,43        7.47%                          Despues del dia 21                         Online (E-Commerce)         Plan 1 cuota            Estandard
Mueble Organizador             5   3.36%      $46.839,54  $234.197,69        6.83%                         Entre el dia 1 y 10                         Presencial (Posnet)        Plan 3 cuotas            Estandard
Accesorios                    13   8.72%      $15.527,57  $201.858,35        5.88%                        Entre el dia 11 y 20                         Online (E-Commerce)         Plan 1 cuota                 Bajo
Cena Restaurante              16  10.74%      $11.072,60  $177.161,64        5.16%                        Entre el dia 11 y 20  [Online (E-Commerce), Presencial (Posnet)]         Plan 1 cuota                 Bajo
Zapatillas Deportivas          6   4.03%      $25.487,20  $152.923,17        4.46%                          Despues del dia 21  [Online (E-Commerce), Presencial (Posnet)]         Plan 1 cuota                 Bajo
Cafetería                     19  12.75%       $5.122,47   $97.326,88        2.84%                        Entre el dia 11 y 20                         Online (E-Commerce)         Plan 1 cuota                 Bajo
Decoración                     3   2.01%      $26.060,74   $78.182,22        2.28%                          Despues del dia 21                         Presencial (Posnet)         Plan 1 cuota                 Bajo
Ropa de Abrigo                 3   2.01%      $25.369,72   $76.109,16        2.22%                        Entre el dia 11 y 20                         Presencial (Posnet)         Plan 1 cuota                 Bajo
Delivery Fin de Semana         7    4.7%       $9.821,46   $68.750,24         2.0%  [Despues del dia 21, Entre el dia 11 y 20]                         Online (E-Commerce)         Plan 1 cuota                 Bajo
Suscripción Streaming         18  12.08%       $2.499,00   $44.982,00        1.31%                        Entre el dia 11 y 20                           Débito Automático         Plan 1 cuota                 Bajo
Accesorios PC                  1   0.67%      $32.537,49   $32.537,49        0.95%                          Despues del dia 21                         Online (E-Commerce)        Plan 3 cuotas                 Bajo
Peajes Automatizados           4   2.68%       $7.860,74   $31.442,96        0.92%                         Entre el dia 1 y 10                         Presencial (Posnet)         Plan 1 cuota                 Bajo
Viaje Plataforma App           1   0.67%       $6.364,57    $6.364,57        0.19%                        Entre el dia 11 y 20                         Presencial (Posnet)         Plan 1 cuota                 Bajo

In [ ]:
## ANALISIS POR CANAL DE PAGO

In [29]:
analisis_canal_pago = df.groupby("Canal_Pago").agg(
    Ventas = ("Id_Transaccion","count"),
    Ticket_Promedio = ("Monto_Pesos","mean"),
    Recaudacion = ("Monto_Pesos","sum"),
    Plan_Cuota_Mas_Usado = ("Plan_Cuotas", lambda x: x.mode()),
    Periodo_Con_Mas_Compras = ("Periodo_Compra", lambda x: x.mode())
    
).round(2).sort_values(by = "Ventas", ascending = False)
analisis_canal_pago["%Ventas"] = ((analisis_canal_pago["Ventas"] / analisis_canal_pago["Ventas"].sum())*100).round(2).astype(str) + "%"
analisis_canal_pago["%Recaudacion"] = ((analisis_canal_pago["Recaudacion"] / analisis_canal_pago["Recaudacion"].sum())*100).round(2).astype(str) + "%"

analisis_canal_pago["Ticket_Promedio"] = analisis_canal_pago["Ticket_Promedio"].apply(lambda x: f"${x:,.2f}".replace(",","X").replace(".",",").replace("X","."))
analisis_canal_pago["Recaudacion"] = analisis_canal_pago["Recaudacion"].apply(lambda x: f"${x:,.2f}".replace(",","X").replace(".",",").replace("X","."))

Orden=[
"Ventas",
"%Ventas",
"Ticket_Promedio",
"Recaudacion",
"%Recaudacion",
"Periodo_Con_Mas_Compras",
"Plan_Cuota_Mas_Usado"
]
analisis_canal_pago = analisis_canal_pago[Orden]
analisis_canal_pago

                     Ventas %Ventas Ticket_Promedio    Recaudacion %Recaudacion                     Periodo_Con_Mas_Compras Plan_Cuota_Mas_Usado
Canal_Pago
Online (E-Commerce)      86  57.72%      $30.098,06  $2.588.433,55       75.43%  [Despues del dia 21, Entre el dia 11 y 20]         Plan 1 cuota
Presencial (Posnet)      45   30.2%      $17.733,58    $798.011,11       23.26%                         Entre el dia 1 y 10         Plan 1 cuota
Débito Automático        18  12.08%       $2.499,00     $44.982,00        1.31%                        Entre el dia 11 y 20         Plan 1 cuota

In [ ]:
## ANALISIS POR PLAN DE CUOTAS

In [31]:
analisis_plan_cuota = df.groupby("Plan_Cuotas").agg(
    Ventas = ("Id_Transaccion","count"),
    Ticket_Promedio = ("Monto_Pesos","mean"),
    Recaudacion = ("Monto_Pesos","sum"),
    Periodo_Con_Mas_Compras = ("Periodo_Compra", lambda x: x.mode())
    ).round(2).sort_values(by="Ventas", ascending = False)

analisis_plan_cuota["%Ventas"] = ((analisis_plan_cuota["Ventas"] / analisis_plan_cuota["Ventas"].sum())*100).round(2).astype(str) + "%"
analisis_plan_cuota["%Recaudacion"] = ((analisis_plan_cuota["Recaudacion"] / analisis_plan_cuota["Recaudacion"].sum())*100).round(2).astype(str) + "%"

analisis_plan_cuota["Ticket_Promedio"] = analisis_plan_cuota["Ticket_Promedio"].apply(lambda x: f"${x:,.2f}".replace(",","X").replace(".",",").replace("X","."))
analisis_plan_cuota["Recaudacion"] = analisis_plan_cuota["Recaudacion"].apply(lambda x: f"${x:,.2f}".replace(",","X").replace(".",",").replace("X","."))

Orden = [
"Ventas",
"%Ventas",
"Ticket_Promedio",
"Recaudacion",
"%Recaudacion",
"Periodo_Con_Mas_Compras"
    ]
analisis_plan_cuota = analisis_plan_cuota[Orden]
analisis_plan_cuota

                Ventas %Ventas Ticket_Promedio    Recaudacion %Recaudacion Periodo_Con_Mas_Compras
Plan_Cuotas
Plan 1 cuota       141  94.63%      $19.281,89  $2.718.746,90       79.23%    Entre el dia 11 y 20
Plan 3 cuotas        6   4.03%      $79.739,00    $478.434,01       13.94%      Despues del dia 21
Plan 12 coutas       1   0.67%     $112.101,62    $112.101,62        3.27%    Entre el dia 11 y 20
Plan 6 cuotas        1   0.67%     $122.144,13    $122.144,13        3.56%    Entre el dia 11 y 20